services:
  - type: web
    name: linka
    env: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    disk:
      name: linka-data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: DATA_DIR
        value: /var/data
