const http=require('http'), fs=require('fs'), path=require('path'), crypto=require('crypto');
const express=require('express'), WebSocket=require('ws'), webpush=require('web-push');
const app=express(); const server=http.createServer(app); const wss=new WebSocket.Server({server});
const PORT=process.env.PORT||3000, DATA_DIR=process.env.DATA_DIR||path.join(__dirname), DATA=path.join(DATA_DIR,'data.json');
try{fs.mkdirSync(DATA_DIR,{recursive:true})}catch(e){}
app.use(express.json({limit:'12mb'})); app.use(express.static(path.join(__dirname,'www')));
let db={users:[],contacts:{},messages:{},sessions:{}};
try{if(fs.existsSync(DATA)) db=JSON.parse(fs.readFileSync(DATA,'utf8'));}catch(e){console.error(e)}
db.users??=[]; db.contacts??={}; db.messages??={}; db.sessions??={}; db.pushSubscriptions??={}; db.pushKeys??=null;
if(!db.pushKeys){db.pushKeys=webpush.generateVAPIDKeys(); try{save()}catch(e){console.error(e)}}
webpush.setVapidDetails(process.env.VAPID_SUBJECT||'mailto:linka@localhost', process.env.VAPID_PUBLIC_KEY||db.pushKeys.publicKey, process.env.VAPID_PRIVATE_KEY||db.pushKeys.privateKey);
function save(){fs.writeFileSync(DATA,JSON.stringify(db));}
function id(){return crypto.randomBytes(12).toString('hex')}
function hash(p,s=crypto.randomBytes(16).toString('hex')){return {s, h:crypto.scryptSync(p,s,64).toString('hex')}}
function check(p,u){return crypto.timingSafeEqual(Buffer.from(hash(p,u.s).h,'hex'),Buffer.from(u.h,'hex'))}
function safe(u,self=false){return {id:u.id,username:u.username,name:u.name,status:u.status,photo:u.photo||'',...(self?{chatBg:u.chatBg||''}:{}),lastSeen:u.lastSeen||u.createdAt,online:isUserOnline(u.id),createdAt:u.createdAt}}
function isUserOnline(uid){for(const [token,idv] of sessions)if(idv===uid && [...wss.clients].some(c=>c.readyState===1&&c.token===token))return true;const u=db.users.find(x=>x.id===uid);return !!(u&&u.lastSeen&&Date.now()-u.lastSeen<60000)}
function touch(uid){const u=db.users.find(x=>x.id===uid);if(u){u.lastSeen=Date.now();save()}}
const sessions=new Map();
function auth(req,res,next){const t=(req.headers.authorization||'').replace('Bearer ','');let uid=sessions.get(t)||db.sessions[t];if(uid){sessions.set(t,uid)}if(!uid)return res.status(401).json({error:'Sessão expirada'});req.user=db.users.find(x=>x.id===uid);if(!req.user)return res.status(401).json({error:'Usuário não encontrado'});next()}
function pair(a,b){return [a,b].sort().join(':')}
function sendUser(uid,msg){for(const [token,idv] of sessions){if(idv!==uid)continue;for(const c of wss.clients)if(c.readyState===1&&c.token===token)c.send(JSON.stringify(msg))}}
async function pushUser(uid,payload){const list=db.pushSubscriptions[uid]||[];if(!list.length)return;const next=[];for(const sub of list){try{await webpush.sendNotification(sub,JSON.stringify(payload),{TTL:60}) ;next.push(sub)}catch(e){if(e.statusCode!==404&&e.statusCode!==410)next.push(sub)}}if(next.length!==list.length){db.pushSubscriptions[uid]=next;save()}}
app.post('/api/register',(req,res)=>{let {name,username,password}=req.body||{};name=String(name||'').trim();username=String(username||'').trim().toLowerCase().replace(/^@/,'');password=String(password||'');if(name.length<2||username.length<3||password.length<6)return res.status(400).json({error:'Use nome, usuário com pelo menos 3 caracteres e senha com 6 caracteres.'});if(!/^[a-z0-9._-]+$/.test(username))return res.status(400).json({error:'Usuário: apenas letras, números, ponto, _ ou -.'});if(db.users.some(u=>u.username===username))return res.status(409).json({error:'Esse usuário já existe.'});const x=hash(password),u={id:id(),name,username,status:'Disponível',photo:'',s:x.s,h:x.h,createdAt:Date.now()};db.users.push(u);db.contacts[u.id]=[];save();const token=id();sessions.set(token,u.id);db.sessions[token]=u.id;save();res.json({token,user:safe(u,true)});});
app.post('/api/login',(req,res)=>{const username=String(req.body?.username||'').trim().toLowerCase().replace(/^@/,'');const password=String(req.body?.password||'');const u=db.users.find(x=>x.username===username);if(!u||!check(password,u))return res.status(401).json({error:'Usuário ou senha inválidos.'});const token=id();sessions.set(token,u.id);db.sessions[token]=u.id;save();res.json({token,user:safe(u,true)});});
app.post('/api/logout',auth,(req,res)=>{touch(req.user.id);for(const [t,u] of sessions)if(u===req.user.id){sessions.delete(t);delete db.sessions[t]}for(const t of Object.keys(db.sessions))if(db.sessions[t]===req.user.id)delete db.sessions[t];save();res.json({ok:true})});
app.post('/api/ping',auth,(req,res)=>{touch(req.user.id);res.json({ok:true,lastSeen:req.user.lastSeen})});
app.get('/api/me',auth,(req,res)=>res.json({user:safe(req.user,true)}));
app.put('/api/me',auth,(req,res)=>{const {name,status,photo,chatBg}=req.body||{};if(typeof name==='string'&&name.trim())req.user.name=name.trim().slice(0,40);if(typeof status==='string')req.user.status=status.trim().slice(0,100);if(typeof photo==='string'&&photo.length<1500000)req.user.photo=photo;if(typeof chatBg==='string'&&chatBg.length<1500000)req.user.chatBg=chatBg;save();res.json({user:safe(req.user,true)});});
app.get('/api/users',auth,(req,res)=>{const q=String(req.query.q||'').trim().toLowerCase().replace(/^@/,'');if(q.length<2)return res.json([]);res.json(db.users.filter(u=>u.id!==req.user.id&&(u.username.includes(q)||u.name.toLowerCase().includes(q))).slice(0,20).map(safe));});
app.get('/api/contacts',auth,(req,res)=>{const ids=db.contacts[req.user.id]||[];res.json(ids.map(i=>db.users.find(u=>u.id===i)).filter(Boolean).map(safe));});
app.get('/api/users/:id',auth,(req,res)=>{const u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'Usuário não encontrado.'});res.json(safe(u));});
app.post('/api/contacts/:id',auth,(req,res)=>{const other=db.users.find(u=>u.id===req.params.id);if(!other||other.id===req.user.id)return res.status(404).json({error:'Usuário não encontrado.'});db.contacts[req.user.id]??=[];if(!db.contacts[req.user.id].includes(other.id))db.contacts[req.user.id].push(other.id);save();sendUser(other.id,{type:'contact_added',by:safe(req.user)});res.json({user:safe(other)});});
app.delete('/api/contacts/:id',auth,(req,res)=>{db.contacts[req.user.id]=(db.contacts[req.user.id]||[]).filter(x=>x!==req.params.id);save();res.json({ok:true});});
app.get('/api/push/vapid-public-key',auth,(req,res)=>res.json({publicKey:process.env.VAPID_PUBLIC_KEY||db.pushKeys.publicKey}));
app.post('/api/push/subscribe',auth,(req,res)=>{const sub=req.body?.subscription;if(!sub||!sub.endpoint||!sub.keys?.p256dh||!sub.keys?.auth)return res.status(400).json({error:'Assinatura de notificação inválida.'});db.pushSubscriptions[req.user.id]??=[];const list=db.pushSubscriptions[req.user.id];if(!list.some(x=>x.endpoint===sub.endpoint))list.push(sub);db.pushSubscriptions[req.user.id]=list.slice(-5);save();res.json({ok:true})});
app.delete('/api/push/subscribe',auth,(req,res)=>{const endpoint=String(req.body?.endpoint||'');if(endpoint)db.pushSubscriptions[req.user.id]=(db.pushSubscriptions[req.user.id]||[]).filter(x=>x.endpoint!==endpoint);save();res.json({ok:true})});
app.get('/api/messages/:id',auth,(req,res)=>{const other=req.params.id;if(!db.users.some(u=>u.id===other))return res.status(404).json({error:'Usuário não encontrado.'});res.json(db.messages[pair(req.user.id,other)]||[]);});
app.post('/api/messages/:id',auth,(req,res)=>{const other=req.params.id;const u=db.users.find(x=>x.id===other);if(!u)return res.status(404).json({error:'Usuário não encontrado.'});let m;if(req.body?.type==='audio'){const audio=String(req.body?.audio||'');if(!/^data:audio\/[A-Za-z0-9.+-]+(?:;[^,]*)?;base64,[A-Za-z0-9+/=]+$/.test(audio)||audio.length>10*1024*1024)return res.status(400).json({error:'Áudio inválido ou muito grande.'});m={id:id(),from:req.user.id,to:other,type:'audio',audio,createdAt:Date.now()};}else{const text=String(req.body?.text||'').trim();if(!text||text.length>4000)return res.status(400).json({error:'Mensagem inválida.'});m={id:id(),from:req.user.id,to:other,type:'text',text,createdAt:Date.now()};}const k=pair(req.user.id,other);db.messages[k]??=[];db.messages[k].push(m);db.messages[k]=db.messages[k].slice(-500);save();sendUser(other,{type:'message',message:m});const preview=m.type==='audio'?'Áudio recebido':m.text;pushUser(other,{title:req.user.name||'Nova mensagem',body:preview,icon:'/icon-192.png',badge:'/icon-192.png',data:{chatId:req.user.id}}).catch(()=>{});res.json(m);});
app.get(/.*/,(req,res)=>res.sendFile(path.join(__dirname,'www','index.html')));
wss.on('connection',(ws,req)=>{const token=new URL(req.url,'http://localhost').searchParams.get('token');const uid=sessions.get(token);if(!uid){ws.close();return}ws.token=token;touch(uid);ws.on('message',buf=>{try{const d=JSON.parse(buf);if(d.type==='ping')touch(uid); if(d.type==='typing' && d.to){sendUser(d.to,{type:'typing',from:uid,active:!!d.active})}}catch{}});ws.on('close',()=>{touch(uid);sendUser(uid,{type:'presence',id:uid});});sendUser(uid,{type:'presence',id:uid});});
server.listen(PORT,()=>console.log('Almeida Chat rodando na porta '+PORT));
