name: Gerar APK Android

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  construir:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v5

      - name: Configurar Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Instalar dependências
        run: |
          npm install
          npm install --save-dev typescript

      - name: Criar projeto Android
        run: |
          npx cap add android
          npx cap sync android

      - name: Dar permissão ao Gradle
        run: chmod +x android/gradlew

      - name: Gerar APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Disponibilizar APK
        uses: actions/upload-artifact@v4
        with:
          name: Linka-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
